version: "2"

services:
  db:
    image: mariadb:10.4.24
    restart: always
    volumes:
      - data:/var/lib/mysq
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '1234'

volumes:
  data: