version: '3.1'

services:
  db:
    image: mariadb:10.4.24
    restart: always
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${DEV_LOCAL_MARIADB_ROOT_PW}
volumes:
  data: