spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:filtering;MODE=MariaDB
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      defer-datasource-initialization: true
  h2:
    console.enabled: true